name: usta_top
description: Usta Top avto servis ilovasi
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.9
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^21.0.0
  http: ^1.2.2
  shared_preferences: ^2.5.5
  provider: ^6.1.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6
  yandex_mapkit: ^4.2.1
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  cli_util: ^0.5.0
  latlong2: ^0.10.1
  matcher: ^0.12.20
  meta: ^1.18.2
  native_toolchain_c: ^0.18.0
  package_info_plus: ^10.1.0
  package_info_plus_platform_interface: ^4.1.0
  test_api: ^0.7.12
  vector_math: ^2.3.0
  win32: ^6.1.0
  xml: ^7.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  android: true
  ios: true
  web: false
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/images/logo.png
    image_dark: assets/images/logo.png
