name: usta_top
description: Usta Top avto servis ilovasi
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6
  yandex_mapkit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/icon.png
  image_dark: assets/images/icon.png
  android: true
  ios: true
  web: false
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/images/icon.png
    image_dark: assets/images/icon.png
