name: usta_top_backend
description: Backend API for Usta Top auto service app
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  excel: ^4.0.6
  googleapis_auth: ^2.0.0
  http: ^1.2.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
